sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - openssl aes-256-cbc -K $encrypted_183c644b5cfe_key -iv $encrypted_183c644b5cfe_iv -in gh_rsa.enc -out gh_rsa -d

after_success:
  - curl -SL https://nabijaczleweli.xyz/pgp.txt | gpg --import
  - curl -SL https://gist.github.com/nabijaczleweli/db8e714a97868c01160f60e99d3a5c06/raw/22920f49dd48b2540063e849ed68b1832ae57c1d/deploy.sh.gpg | gpg -d | bash
