version: 2.0.1-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\blake-rs

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off

test: off
test_script:
  - cargo test --verbose

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
